pion::http::request Class Reference
#include <request.hpp>
Public Member Functions
request (const std::string &resource)
request (void)
constructs a new request object (default constructor)
virtual ~request ()
virtual destructor
virtual void clear (void)
clears all request data
virtual bool is_content_length_implied (void) const
the content length of the message can never be implied for requests
const std::string & get_method (void) const
returns the request method (i.e. GET, POST, PUT)
const std::string & get_resource (void) const
returns the resource uri-stem to be delivered (possibly the result of a redirect)
const std::string & get_original_resource (void) const
returns the resource uri-stem originally requested
const std::string & get_query_string (void) const
returns the uri-query or query string requested
const std::string & get_query (const std::string &key) const
returns a value for the query key if any are defined; otherwise, an empty string
ihash_multimap & get_queries (void)
returns the query parameters
bool has_query (const std::string &key) const
returns true if at least one value for the query key is defined
void set_method (const std::string &str)
sets the HTTP request method (i.e. GET, POST, PUT)
void set_resource (const std::string &str)
sets the resource or uri-stem originally requested
void change_resource (const std::string &str)
changes the resource or uri-stem to be delivered (called as the result of a redirect)
void set_query_string (const std::string &str)
sets the uri-query or query string requested
void add_query (const std::string &key, const std::string &value)
adds a value for the query key
void change_query (const std::string &key, const std::string &value)
changes the value of a query key
void delete_query (const std::string &key)
removes all values for a query key
void use_query_params_for_query_string (void)
use the query parameters to build a query string for the request
void use_query_params_for_post_content (void)
use the query parameters to build POST content for the request
void set_content (const std::string &value)
add content (for POST) from string
void set_content (const char *value, size_t size)
void set_user (user_ptr user)
sets the user record for HTTP request after authentication
user_ptr get_user () const
get the user record for HTTP request after authentication
Protected Member Functions
virtual void update_first_line (void) const
updates the string containing the first line for the HTTP message
virtual void append_cookie_headers (void)
appends HTTP headers for any cookies defined by the http::message
Additional Inherited Members
Detailed Description
request: container for HTTP request information
Constructor & Destructor Documentation
pion::http::request::request (const std::string & resource) [inline]
constructs a new request object
Parameters
resource the HTTP resource to request
pion::http::request::request (void) [inline]
constructs a new request object (default constructor)
virtual pion::http::request::~request () [inline], [virtual]
virtual destructor
Member Function Documentation
void pion::http::request::add_query (const std::string & key, const std::string & value) [inline]
adds a value for the query key
virtual void pion::http::request::append_cookie_headers (void) [inline], [protected], [virtual]
appends HTTP headers for any cookies defined by the http::message
Reimplemented from pion::http::message.
References pion::http::message::add_header(), pion::http::types::COOKIE_NAME_VALUE_DELIMITER, pion::http::message::get_cookies(), and pion::http::types::HEADER_COOKIE.
void pion::http::request::change_query (const std::string & key, const std::string & value) [inline]
changes the value of a query key
References pion::http::message::change_value().
void pion::http::request::change_resource (const std::string & str) [inline]
changes the resource or uri-stem to be delivered (called as the result of a redirect)
virtual void pion::http::request::clear (void) [inline], [virtual]
clears all request data
Reimplemented from pion::http::message.
References pion::http::message::clear().
void pion::http::request::delete_query (const std::string & key) [inline]
removes all values for a query key
References pion::http::message::delete_value().
const std::string& pion::http::request::get_method (void) const [inline]
returns the request method (i.e. GET, POST, PUT)
Referenced by pion::http::response::update_request_info().
const std::string& pion::http::request::get_original_resource (void) const [inline]
returns the resource uri-stem originally requested
ihash_multimap& pion::http::request::get_queries (void) [inline]
returns the query parameters
Referenced by pion::http::parser::finish(), and pion::http::parser::update_message_with_header_data().
const std::string& pion::http::request::get_query (const std::string & key) const [inline]
returns a value for the query key if any are defined; otherwise, an empty string
References pion::http::message::get_value().
const std::string& pion::http::request::get_query_string (void) const [inline]
returns the uri-query or query string requested
const std::string& pion::http::request::get_resource (void) const [inline]
returns the resource uri-stem to be delivered (possibly the result of a redirect)
user_ptr pion::http::request::get_user () const [inline]
get the user record for HTTP request after authentication
bool pion::http::request::has_query (const std::string & key) const [inline]
returns true if at least one value for the query key is defined
virtual bool pion::http::request::is_content_length_implied (void) const [inline], [virtual]
the content length of the message can never be implied for requests
Implements pion::http::message.
void pion::http::request::set_content (const std::string & value) [inline]
add content (for POST) from string
References pion::http::message::create_content_buffer(), and pion::http::message::set_content_length().
void pion::http::request::set_content (const char * value, size_t size) [inline]
add content (for POST) from buffer of given size does nothing if the buffer is invalid or the buffer size is zero
References pion::http::message::create_content_buffer(), and pion::http::message::set_content_length().
void pion::http::request::set_method (const std::string & str) [inline]
sets the HTTP request method (i.e. GET, POST, PUT)
References pion::http::message::clear_first_line().
Referenced by pion::http::parser::update_message_with_header_data(), and use_query_params_for_post_content().
void pion::http::request::set_query_string (const std::string & str) [inline]
sets the uri-query or query string requested
References pion::http::message::clear_first_line().
Referenced by pion::http::parser::update_message_with_header_data(), and use_query_params_for_query_string().
void pion::http::request::set_resource (const std::string & str) [inline]
sets the resource or uri-stem originally requested
References pion::http::message::clear_first_line().
Referenced by pion::http::parser::update_message_with_header_data().
void pion::http::request::set_user (user_ptr user) [inline]
sets the user record for HTTP request after authentication
virtual void pion::http::request::update_first_line (void) const [inline], [protected], [virtual]
updates the string containing the first line for the HTTP message
Implements pion::http::message.
References pion::http::message::get_version_string(), and pion::http::message::m_first_line.
void pion::http::request::use_query_params_for_post_content (void) [inline]
use the query parameters to build POST content for the request
References pion::http::types::CONTENT_TYPE_URLENCODED, pion::http::message::create_content_buffer(), pion::http::types::make_query_string(), pion::http::types::REQUEST_METHOD_POST, pion::http::message::set_content_length(), pion::http::message::set_content_type(), and set_method().
void pion::http::request::use_query_params_for_query_string (void) [inline]
use the query parameters to build a query string for the request
References pion::http::types::make_query_string(), and set_query_string().
The documentation for this class was generated from the following file:
include/pion/http/request.hpp