log4cplus::DeviceAppender< Device > Class Template Reference
#include <deviceappender.hxx>
Public Types
typedef
*
device_appender_detail::device_type_traits
*
< Device > device_traits
typedef device_traits::device_type device_type
Public Member Functions
template<typename D >
DeviceAppender (D &d, bool close_device=true)
template<typename D >
DeviceAppender (boost::shared_ptr< D > const &d, bool close_device=true)
template<typename D >
DeviceAppender (D &d, const helpers::Properties &props)
template<typename D >
DeviceAppender (boost::shared_ptr< D > const &d, const helpers::Properties &props)
virtual ~DeviceAppender ()
virtual void close ()
Protected Member Functions
virtual void append (log4cplus::spi::InternalLoggingEvent const &event)
Protected Attributes
device_type device
bool close_flag
Additional Inherited Members
Member Typedef Documentation
template<typename Device > typedef device_appender_detail::device_type_traits<Device> log4cplus::DeviceAppender< Device >::device_traits
template<typename Device > typedef device_traits::device_type log4cplus::DeviceAppender< Device >::device_type
Constructor & Destructor Documentation
template<typename Device > template<typename D > log4cplus::DeviceAppender< Device >::DeviceAppender (D & d, bool close_device = true) [inline]
template<typename Device > template<typename D > log4cplus::DeviceAppender< Device >::DeviceAppender (boost::shared_ptr< D > const & d, bool close_device = true) [inline]
template<typename Device > template<typename D > log4cplus::DeviceAppender< Device >::DeviceAppender (D & d, const helpers::Properties & props) [inline]
References log4cplus::DeviceAppender< Device >::close_flag, log4cplus::helpers::Properties::exists(), and LOG4CPLUS_TEXT.
template<typename Device > template<typename D > log4cplus::DeviceAppender< Device >::DeviceAppender (boost::shared_ptr< D > const & d, const helpers::Properties & props) [inline]
References log4cplus::DeviceAppender< Device >::close_flag, log4cplus::helpers::Properties::exists(), and LOG4CPLUS_TEXT.
template<typename Device > virtual log4cplus::DeviceAppender< Device >::~DeviceAppender () [inline], [virtual]
Member Function Documentation
template<typename Device > virtual void log4cplus::DeviceAppender< Device >::append (log4cplus::spi::InternalLoggingEvent const & event) [inline], [protected], [virtual]
Subclasses of Appender should implement this method to perform actual logging.
See Also
doAppend method.
Implements log4cplus::Appender.
References log4cplus::DeviceAppender< Device >::device, log4cplus::Appender::formatEvent(), log4cplus::device_appender_detail::device_type_traits< T >::unwrap(), and log4cplus::helpers::write().
template<typename Device > virtual void log4cplus::DeviceAppender< Device >::close () [inline], [virtual]
Release any resources allocated within the appender such as file handles, network connections, etc.
It is a programming error to append to a closed appender.
Implements log4cplus::Appender.
References log4cplus::DeviceAppender< Device >::close_flag, log4cplus::DeviceAppender< Device >::device, and log4cplus::device_appender_detail::device_type_traits< T >::unwrap().
Member Data Documentation
template<typename Device > bool log4cplus::DeviceAppender< Device >::close_flag [protected]
Referenced by log4cplus::DeviceAppender< Device >::close(), and log4cplus::DeviceAppender< Device >::DeviceAppender().
template<typename Device > device_type log4cplus::DeviceAppender< Device >::device [protected]
Referenced by log4cplus::DeviceAppender< Device >::append(), and log4cplus::DeviceAppender< Device >::close().
The documentation for this class was generated from the following file:
/home/roger/NetBeansProjects/log4cplus/include/log4cplus/boost/deviceappender.hxx