pion::process Class Reference
#include <process.hpp>
Classes
struct config_type
data type for static/global process configuration information
Public Member Functions
~process ()
process (void)
default constructor
Static Public Member Functions
static void shutdown (void)
signals the shutdown condition
static void wait_for_shutdown (void)
blocks until the shutdown condition has been signaled
static void initialize (void)
sets up basic signal handling for the process
static void daemonize (void)
fork process and run as a background daemon
Static Protected Member Functions
static config_type & get_config (void)
returns a singleton instance of config_type
Detailed Description
process: class for managing process/service related functions
Constructor & Destructor Documentation
pion::process::~process () [inline]
pion::process::process (void) [inline]
default constructor
Member Function Documentation
void pion::process::daemonize (void) [static]
fork process and run as a background daemon
static config_type& pion::process::get_config (void) [inline], [static], [protected]
returns a singleton instance of config_type
Referenced by shutdown(), and wait_for_shutdown().
void pion::process::initialize (void) [static]
sets up basic signal handling for the process
References pion::handle_signal().
void pion::process::shutdown (void) [static]
signals the shutdown condition
References get_config(), pion::process::config_type::shutdown_cond, pion::process::config_type::shutdown_mutex, and pion::process::config_type::shutdown_now.
Referenced by pion::handle_signal().
void pion::process::wait_for_shutdown (void) [static]
blocks until the shutdown condition has been signaled
References get_config(), pion::process::config_type::shutdown_cond, pion::process::config_type::shutdown_mutex, and pion::process::config_type::shutdown_now.
The documentation for this class was generated from the following files:
include/pion/process.hpp
src/process.cpp