pion::http::response_reader Class Reference
#include <response_reader.hpp>
Public Types
typedef boost::function3< void,
*
http::response_ptr,
*
tcp::connection_ptr, const
*
boost::system::error_code & > finished_handler_t
function called after the HTTP message has been parsed
Public Member Functions
virtual ~response_reader ()
void set_headers_parsed_callback (finished_handler_t &h)
sets a function to be called after HTTP headers have been parsed
Static Public Member Functions
static boost::shared_ptr
*
< response_reader > create (const tcp::connection_ptr &tcp_conn, const http::request &http_request, finished_handler_t handler)
Protected Member Functions
response_reader (const tcp::connection_ptr &tcp_conn, const http::request &http_request, finished_handler_t handler)
virtual void read_bytes (void)
Reads more bytes from the TCP connection.
virtual void finished_parsing_headers (const boost::system::error_code &ec)
Called after we have finished parsing the HTTP message headers.
virtual void finished_reading (const boost::system::error_code &ec)
Called after we have finished reading/parsing the HTTP message.
virtual http::message & get_message (void)
Returns a reference to the HTTP message being parsed.
Protected Attributes
http::response_ptr m_http_msg
The new HTTP message container being created.
finished_handler_t m_finished
function called after the HTTP message has been parsed
finished_handler_t m_parsed_headers
function called after the HTTP message headers have been parsed
Additional Inherited Members
Detailed Description
response_reader: asynchronously reads and parses HTTP responses
Member Typedef Documentation
typedef boost::function3<void, http::response_ptr, tcp::connection_ptr, const boost::system::error_code&> pion::http::response_reader::finished_handler_t
function called after the HTTP message has been parsed
Constructor & Destructor Documentation
virtual pion::http::response_reader::~response_reader () [inline], [virtual]
pion::http::response_reader::response_reader (const tcp::connection_ptr & tcp_conn, const http::request & http_request, finished_handler_t handler) [inline], [protected]
protected constructor restricts creation of objects (use create())
Parameters
tcp_conn TCP connection containing a new message to parse
http_request the request we are responding to
handler function called after the message has been parsed
References m_http_msg, PION_GET_LOGGER, and pion::http::parser::set_logger().
Referenced by create().
Member Function Documentation
static boost::shared_ptr<response_reader> pion::http::response_reader::create (const tcp::connection_ptr & tcp_conn, const http::request & http_request, finished_handler_t handler) [inline], [static]
creates new response_reader objects
Parameters
tcp_conn TCP connection containing a new message to parse
http_request the request we are responding to
handler function called after the message has been parsed
References response_reader().
virtual void pion::http::response_reader::finished_parsing_headers (const boost::system::error_code & ec) [inline], [protected], [virtual]
Called after we have finished parsing the HTTP message headers.
Reimplemented from pion::http::parser.
References pion::http::reader::get_connection(), m_http_msg, and m_parsed_headers.
virtual void pion::http::response_reader::finished_reading (const boost::system::error_code & ec) [inline], [protected], [virtual]
Called after we have finished reading/parsing the HTTP message.
Implements pion::http::reader.
References pion::http::reader::get_connection(), m_finished, and m_http_msg.
virtual http::message& pion::http::response_reader::get_message (void) [inline], [protected], [virtual]
Returns a reference to the HTTP message being parsed.
Implements pion::http::reader.
References m_http_msg.
virtual void pion::http::response_reader::read_bytes (void) [inline], [protected], [virtual]
Reads more bytes from the TCP connection.
Implements pion::http::reader.
References pion::http::reader::consume_bytes(), and pion::http::reader::get_connection().
void pion::http::response_reader::set_headers_parsed_callback (finished_handler_t & h) [inline]
sets a function to be called after HTTP headers have been parsed
References m_parsed_headers.
Member Data Documentation
finished_handler_t pion::http::response_reader::m_finished [protected]
function called after the HTTP message has been parsed
Referenced by finished_reading().
http::response_ptr pion::http::response_reader::m_http_msg [protected]
The new HTTP message container being created.
Referenced by finished_parsing_headers(), finished_reading(), get_message(), and response_reader().
finished_handler_t pion::http::response_reader::m_parsed_headers [protected]
function called after the HTTP message headers have been parsed
Referenced by finished_parsing_headers(), and set_headers_parsed_callback().
The documentation for this class was generated from the following file:
include/pion/http/response_reader.hpp