pion::exception Class Reference
#include <error.hpp>
Public Member Functions
exception ()
exception (const std::string &msg)
exception (const char *const msg)
virtual ~exception () throw ()
virtual const char * what () const throw ()
Protected Member Functions
void set_what_msg (const char *const msg=NULL, const std::string *const arg1=NULL, const std::string *const arg2=NULL, const std::string *const arg3=NULL) const
virtual void update_what_msg () const
Protected Attributes
std::string m_what_msg
Constructor & Destructor Documentation
pion::exception::exception () [inline]
pion::exception::exception (const std::string & msg) [inline]
pion::exception::exception (const char *const msg) [inline]
virtual pion::exception::~exception () throw) [inline], [virtual]
Member Function Documentation
void pion::exception::set_what_msg (const char *const msg = NULL, const std::string *const arg1 = NULL, const std::string *const arg2 = NULL, const std::string *const arg3 = NULL) const [inline], [protected]
References m_what_msg.
Referenced by update_what_msg().
virtual void pion::exception::update_what_msg () const [inline], [protected], [virtual]
References set_what_msg().
Referenced by what().
virtual const char* pion::exception::what () const throw) [inline], [virtual]
References m_what_msg, and update_what_msg().
Member Data Documentation
std::string pion::exception::m_what_msg [mutable], [protected]
Referenced by set_what_msg(), and what().
The documentation for this class was generated from the following file:
include/pion/error.hpp