pion::plugin_instance_ptr< InterfaceClassType > Class Template Reference
#include <plugin.hpp>
Public Member Functions
plugin_instance_ptr (void)
default constructor & destructor
virtual ~plugin_instance_ptr ()
virtual destructor / may be extended
void reset (void)
reset the instance pointer
void create (const std::string &plugin_type)
create a new instance of the given plugin_type
bool empty (void) const
returns true if pointer is empty
InterfaceClassType * get (void)
return a raw pointer to the instance
InterfaceClassType & operator* (void)
return a reference to the instance
const InterfaceClassType & operator* (void) const
return a const reference to the instance
InterfaceClassType * operator-> (void)
return a reference to the instance
const InterfaceClassType * operator-> (void) const
return a const reference to the instance
Protected Attributes
plugin_ptr< InterfaceClassType > m_plugin_ptr
smart pointer that manages the plugin's dynamic object code
InterfaceClassType * m_instance_ptr
raw pointer to the plugin instance
Detailed Description
template<typename InterfaceClassType>class pion::plugin_instance_ptr< InterfaceClassType >
plugin_instance_ptr: smart pointer that manages a plug-in instance
Constructor & Destructor Documentation
template<typename InterfaceClassType > pion::plugin_instance_ptr< InterfaceClassType >::plugin_instance_ptr (void) [inline]
default constructor & destructor
template<typename InterfaceClassType > virtual pion::plugin_instance_ptr< InterfaceClassType >::~plugin_instance_ptr () [inline], [virtual]
virtual destructor / may be extended
References pion::plugin_instance_ptr< InterfaceClassType >::reset().
Member Function Documentation
template<typename InterfaceClassType > void pion::plugin_instance_ptr< InterfaceClassType >::create (const std::string & plugin_type) [inline]
create a new instance of the given plugin_type
References pion::plugin_instance_ptr< InterfaceClassType >::m_instance_ptr, pion::plugin_instance_ptr< InterfaceClassType >::m_plugin_ptr, and pion::plugin_instance_ptr< InterfaceClassType >::reset().
template<typename InterfaceClassType > bool pion::plugin_instance_ptr< InterfaceClassType >::empty (void) const [inline]
returns true if pointer is empty
References pion::plugin_instance_ptr< InterfaceClassType >::m_instance_ptr.
template<typename InterfaceClassType > InterfaceClassType* pion::plugin_instance_ptr< InterfaceClassType >::get (void) [inline]
return a raw pointer to the instance
References pion::plugin_instance_ptr< InterfaceClassType >::m_instance_ptr.
template<typename InterfaceClassType > InterfaceClassType& pion::plugin_instance_ptr< InterfaceClassType >::operator* (void) [inline]
return a reference to the instance
References pion::plugin_instance_ptr< InterfaceClassType >::m_instance_ptr.
template<typename InterfaceClassType > const InterfaceClassType& pion::plugin_instance_ptr< InterfaceClassType >::operator* (void) const [inline]
return a const reference to the instance
References pion::plugin_instance_ptr< InterfaceClassType >::m_instance_ptr.
template<typename InterfaceClassType > InterfaceClassType* pion::plugin_instance_ptr< InterfaceClassType >::operator-> (void) [inline]
return a reference to the instance
References pion::plugin_instance_ptr< InterfaceClassType >::m_instance_ptr.
template<typename InterfaceClassType > const InterfaceClassType* pion::plugin_instance_ptr< InterfaceClassType >::operator-> (void) const [inline]
return a const reference to the instance
References pion::plugin_instance_ptr< InterfaceClassType >::m_instance_ptr.
template<typename InterfaceClassType > void pion::plugin_instance_ptr< InterfaceClassType >::reset (void) [inline]
reset the instance pointer
References pion::plugin_instance_ptr< InterfaceClassType >::m_instance_ptr, and pion::plugin_instance_ptr< InterfaceClassType >::m_plugin_ptr.
Referenced by pion::plugin_instance_ptr< InterfaceClassType >::create(), and pion::plugin_instance_ptr< InterfaceClassType >::~plugin_instance_ptr().
Member Data Documentation
template<typename InterfaceClassType > InterfaceClassType* pion::plugin_instance_ptr< InterfaceClassType >::m_instance_ptr [protected]
raw pointer to the plugin instance
Referenced by pion::plugin_instance_ptr< InterfaceClassType >::create(), pion::plugin_instance_ptr< InterfaceClassType >::empty(), pion::plugin_instance_ptr< InterfaceClassType >::get(), pion::plugin_instance_ptr< InterfaceClassType >::operator*(), pion::plugin_instance_ptr< InterfaceClassType >::operator->(), and pion::plugin_instance_ptr< InterfaceClassType >::reset().
template<typename InterfaceClassType > plugin_ptr<InterfaceClassType> pion::plugin_instance_ptr< InterfaceClassType >::m_plugin_ptr [protected]
smart pointer that manages the plugin's dynamic object code
Referenced by pion::plugin_instance_ptr< InterfaceClassType >::create(), and pion::plugin_instance_ptr< InterfaceClassType >::reset().
The documentation for this class was generated from the following file:
include/pion/plugin.hpp