pion::http::message::content_buffer_t Class Reference
a simple helper class used to manage a fixed-size payload content buffer
#include <message.hpp>
Public Member Functions
~content_buffer_t ()
simple destructor
content_buffer_t ()
default constructor
content_buffer_t (const content_buffer_t &buf)
copy constructor
content_buffer_t & operator= (const content_buffer_t &buf)
assignment operator
bool is_empty () const
returns true if buffer is empty
std::size_t size () const
returns size in bytes
const char * get () const
returns const pointer to data
char * get ()
returns mutable pointer to data
void resize (std::size_t len)
changes the size of the content buffer
void clear ()
clears the content buffer
Detailed Description
a simple helper class used to manage a fixed-size payload content buffer
Constructor & Destructor Documentation
pion::http::message::content_buffer_t::~content_buffer_t () [inline]
simple destructor
pion::http::message::content_buffer_t::content_buffer_t () [inline]
default constructor
pion::http::message::content_buffer_t::content_buffer_t (const content_buffer_t & buf) [inline]
copy constructor
References get(), and size().
Member Function Documentation
void pion::http::message::content_buffer_t::clear (void) [inline]
clears the content buffer
const char* pion::http::message::content_buffer_t::get () const [inline]
returns const pointer to data
Referenced by content_buffer_t(), and operator=().
char* pion::http::message::content_buffer_t::get () [inline]
returns mutable pointer to data
bool pion::http::message::content_buffer_t::is_empty () const [inline]
returns true if buffer is empty
content_buffer_t& pion::http::message::content_buffer_t::operator= (const content_buffer_t & buf) [inline]
assignment operator
References get(), and size().
void pion::http::message::content_buffer_t::resize (std::size_t len) [inline]
changes the size of the content buffer
std::size_t pion::http::message::content_buffer_t::size () const [inline]
returns size in bytes
Referenced by content_buffer_t(), and operator=().
The documentation for this class was generated from the following file:
include/pion/http/message.hpp