pion::http::reader Class Reference
#include <reader.hpp>
Public Member Functions
virtual ~reader ()
void receive (void)
Incrementally reads & parses the HTTP message.
tcp::connection_ptr & get_connection (void)
returns a shared pointer to the TCP connection
void set_timeout (boost::uint32_t seconds)
sets the maximum number of seconds for read operations
Protected Member Functions
reader (const bool is_request, const tcp::connection_ptr &tcp_conn)
void consume_bytes (const boost::system::error_code &read_error, std::size_t bytes_read)
void consume_bytes (void)
Consumes bytes that have been read using an HTTP parser.
virtual void read_bytes (void)=0
Reads more bytes from the TCP connection.
virtual void finished_reading (const boost::system::error_code &ec)=0
Called after we have finished reading/parsing the HTTP message.
virtual http::message & get_message (void)=0
Returns a reference to the HTTP message being parsed.
Additional Inherited Members
Detailed Description
reader: asynchronously reads and parses HTTP messages
Constructor & Destructor Documentation
virtual pion::http::reader::~reader () [inline], [virtual]
pion::http::reader::reader (const bool is_request, const tcp::connection_ptr & tcp_conn) [inline], [protected]
protected constructor: only derived classes may create objects
Parameters
is_request if true, the message is parsed as an HTTP request; if false, the message is parsed as an HTTP response
tcp_conn TCP connection containing a new message to parse
Member Function Documentation
void pion::http::reader::consume_bytes (const boost::system::error_code & read_error, std::size_t bytes_read) [protected]
Consumes bytes that have been read using an HTTP parser
Parameters
read_error error status from the last read operation
bytes_read number of bytes consumed by the last read operation
References consume_bytes(), pion::http::parser::is_parsing_request(), pion::http::parser::m_logger, PION_LOG_DEBUG, and pion::http::parser::set_read_buffer().
void pion::http::reader::consume_bytes (void) [protected]
Consumes bytes that have been read using an HTTP parser.
References pion::http::parser::bytes_available(), pion::http::parser::eof(), finished_reading(), pion::http::parser::gcount(), get_message(), pion::http::parser::is_parsing_request(), pion::tcp::connection::LIFECYCLE_CLOSE, pion::tcp::connection::LIFECYCLE_KEEPALIVE, pion::tcp::connection::LIFECYCLE_PIPELINED, pion::http::parser::m_logger, pion::http::parser::m_read_end_ptr, pion::http::parser::m_read_ptr, pion::http::parser::parse(), PION_LOG_DEBUG, and pion::http::message::set_is_valid().
Referenced by consume_bytes(), pion::http::request_reader::read_bytes(), pion::http::response_reader::read_bytes(), and receive().
virtual void pion::http::reader::finished_reading (const boost::system::error_code & ec) [protected], [pure virtual]
Called after we have finished reading/parsing the HTTP message.
Implemented in pion::http::response_reader, and pion::http::request_reader.
Referenced by consume_bytes().
tcp::connection_ptr& pion::http::reader::get_connection (void) [inline]
returns a shared pointer to the TCP connection
Referenced by pion::http::request_reader::finished_parsing_headers(), pion::http::response_reader::finished_parsing_headers(), pion::http::request_reader::finished_reading(), pion::http::response_reader::finished_reading(), pion::http::request_reader::read_bytes(), and pion::http::response_reader::read_bytes().
virtual http::message& pion::http::reader::get_message (void) [protected], [pure virtual]
Returns a reference to the HTTP message being parsed.
Implemented in pion::http::response_reader, and pion::http::request_reader.
Referenced by consume_bytes().
virtual void pion::http::reader::read_bytes (void) [protected], [pure virtual]
Reads more bytes from the TCP connection.
Implemented in pion::http::response_reader, and pion::http::request_reader.
void pion::http::reader::receive (void)
Incrementally reads & parses the HTTP message.
References consume_bytes(), pion::tcp::connection::LIFECYCLE_CLOSE, pion::http::parser::m_read_end_ptr, and pion::http::parser::m_read_ptr.
void pion::http::reader::set_timeout (boost::uint32_t seconds) [inline]
sets the maximum number of seconds for read operations
The documentation for this class was generated from the following files:
include/pion/http/reader.hpp
src/http_reader.cpp