pion::tcp::connection::ssl_socket_type Class Reference
#include <connection.hpp>
Public Member Functions
ssl_socket_type (boost::asio::io_service &io_service)
socket_type & next_layer (void)
const socket_type & next_layer (void) const
socket_type::lowest_layer_type & lowest_layer (void)
const
*
socket_type::lowest_layer_type & lowest_layer (void) const
void shutdown (void)
Constructor & Destructor Documentation
pion::tcp::connection::ssl_socket_type::ssl_socket_type (boost::asio::io_service & io_service) [inline]
Member Function Documentation
socket_type::lowest_layer_type& pion::tcp::connection::ssl_socket_type::lowest_layer (void) [inline]
Referenced by pion::tcp::connection::accept(), pion::tcp::connection::async_accept(), pion::tcp::connection::async_connect(), pion::tcp::connection::connect(), and pion::tcp::connection::get_io_service().
const socket_type::lowest_layer_type& pion::tcp::connection::ssl_socket_type::lowest_layer (void) const [inline]
socket_type& pion::tcp::connection::ssl_socket_type::next_layer (void) [inline]
Referenced by pion::tcp::connection::async_read(), pion::tcp::connection::async_read_some(), pion::tcp::connection::async_write(), pion::tcp::connection::cancel(), pion::tcp::connection::close(), pion::tcp::connection::get_socket(), pion::tcp::connection::read(), pion::tcp::connection::read_some(), and pion::tcp::connection::write().
const socket_type& pion::tcp::connection::ssl_socket_type::next_layer (void) const [inline]
void pion::tcp::connection::ssl_socket_type::shutdown (void) [inline]
The documentation for this class was generated from the following file:
include/pion/tcp/connection.hpp