pion::plugin_manager< PluginType >::map_type Class Reference
data type that maps identifiers to plug-in objects
#include <plugin_manager.hpp>
Public Member Functions
void clear (void)
virtual ~map_type ()
map_type (void)
Detailed Description
template<typename PluginType>class pion::plugin_manager< PluginType >::map_type
data type that maps identifiers to plug-in objects
Constructor & Destructor Documentation
template<typename PluginType> virtual pion::plugin_manager< PluginType >::map_type::~map_type () [inline], [virtual]
References pion::plugin_manager< PluginType >::map_type::clear().
template<typename PluginType> pion::plugin_manager< PluginType >::map_type::map_type (void) [inline]
Member Function Documentation
template<typename PluginType> void pion::plugin_manager< PluginType >::map_type::clear (void) [inline]
References pion::plugin_manager< PluginType >::empty().
Referenced by pion::plugin_manager< http::plugin_service >::clear(), and pion::plugin_manager< PluginType >::map_type::~map_type().
The documentation for this class was generated from the following file:
include/pion/plugin_manager.hpp