pion::http::response_writer Class Reference
#include <response_writer.hpp>
Public Member Functions
virtual ~response_writer ()
default destructor
http::response & get_response (void)
returns a non-const reference to the response that will be sent
Static Public Member Functions
static boost::shared_ptr
*
< response_writer > create (const tcp::connection_ptr &tcp_conn, const http::response_ptr &http_response_ptr, finished_handler_t handler=finished_handler_t())
static boost::shared_ptr
*
< response_writer > create (const tcp::connection_ptr &tcp_conn, const http::request &http_request, finished_handler_t handler=finished_handler_t())
Protected Member Functions
response_writer (const tcp::connection_ptr &tcp_conn, const http::response_ptr &http_response_ptr, finished_handler_t handler)
response_writer (const tcp::connection_ptr &tcp_conn, const http::request &http_request, finished_handler_t handler)
virtual void prepare_buffers_for_send (http::message::write_buffers_t &write_buffers)
virtual write_handler_t bind_to_write_handler (void)
returns a function bound to http::writer::handle_write()
virtual void handle_write (const boost::system::error_code &write_error, std::size_t bytes_written)
Additional Inherited Members
Detailed Description
response_writer: used to asynchronously send HTTP responses
Constructor & Destructor Documentation
virtual pion::http::response_writer::~response_writer () [inline], [virtual]
default destructor
pion::http::response_writer::response_writer (const tcp::connection_ptr & tcp_conn, const http::response_ptr & http_response_ptr, finished_handler_t handler) [inline], [protected]
protected constructor restricts creation of objects (use create())
Parameters
tcp_conn TCP connection used to send the response
http_response pointer to the response that will be sent
handler function called after the request has been sent
References PION_GET_LOGGER.
pion::http::response_writer::response_writer (const tcp::connection_ptr & tcp_conn, const http::request & http_request, finished_handler_t handler) [inline], [protected]
protected constructor restricts creation of objects (use create())
Parameters
tcp_conn TCP connection used to send the response
http_request the request we are responding to
handler function called after the request has been sent
References PION_GET_LOGGER.
Member Function Documentation
virtual write_handler_t pion::http::response_writer::bind_to_write_handler (void) [inline], [protected], [virtual]
returns a function bound to http::writer::handle_write()
Implements pion::http::writer.
References handle_write().
static boost::shared_ptr<response_writer> pion::http::response_writer::create (const tcp::connection_ptr & tcp_conn, const http::response_ptr & http_response_ptr, finished_handler_t handler = finished_handler_t()) [inline], [static]
creates new response_writer objects
Parameters
tcp_conn TCP connection used to send the response
http_response pointer to the response that will be sent
handler function called after the response has been sent
Returns
boost::shared_ptr<response_writer> shared pointer to the new writer object that was created
Referenced by pion::http::server::handle_bad_request(), pion::http::server::handle_forbidden_request(), pion::http::server::handle_method_not_allowed(), pion::http::server::handle_not_found_request(), pion::http::cookie_auth::handle_ok(), pion::http::cookie_auth::handle_redirection(), pion::http::server::handle_server_error(), pion::http::basic_auth::handle_unauthorized(), and pion::http::cookie_auth::handle_unauthorized().
static boost::shared_ptr<response_writer> pion::http::response_writer::create (const tcp::connection_ptr & tcp_conn, const http::request & http_request, finished_handler_t handler = finished_handler_t()) [inline], [static]
creates new response_writer objects
Parameters
tcp_conn TCP connection used to send the response
http_request the request we are responding to
handler function called after the request has been sent
Returns
boost::shared_ptr<response_writer> shared pointer to the new writer object that was created
http::response& pion::http::response_writer::get_response (void) [inline]
returns a non-const reference to the response that will be sent
virtual void pion::http::response_writer::handle_write (const boost::system::error_code & write_error, std::size_t bytes_written) [inline], [protected], [virtual]
called after the response is sent
Parameters
write_error error status from the last write operation
bytes_written number of bytes sent by the last write operation
Implements pion::http::writer.
References PION_LOG_DEBUG.
Referenced by bind_to_write_handler().
virtual void pion::http::response_writer::prepare_buffers_for_send (http::message::write_buffers_t & write_buffers) [inline], [protected], [virtual]
initializes a vector of write buffers with the HTTP message information
Parameters
write_buffers vector of write buffers to initialize
Implements pion::http::writer.
The documentation for this class was generated from the following file:
include/pion/http/response_writer.hpp