log4cplus::spi::InternalLoggingEvent Class Reference
#include <loggingevent.h>
Public Member Functions
InternalLoggingEvent (const log4cplus::tstring &logger, LogLevel loglevel, const log4cplus::tstring &message, const char *filename, int line, const char *function=nullptr)
InternalLoggingEvent (const log4cplus::tstring &logger, LogLevel loglevel, const log4cplus::tstring &ndc, MappedDiagnosticContextMap const &mdc, const log4cplus::tstring &message, const log4cplus::tstring &thread, log4cplus::helpers::Time time, const log4cplus::tstring &file, int line, const log4cplus::tstring &function=log4cplus::tstring())
InternalLoggingEvent ()
InternalLoggingEvent (const log4cplus::spi::InternalLoggingEvent &rhs)
virtual ~InternalLoggingEvent ()
void setLoggingEvent (const log4cplus::tstring &logger, LogLevel ll, const log4cplus::tstring &message, const char *filename, int line, const char *function=nullptr)
void setFunction (char const *func)
void setFunction (log4cplus::tstring const &)
virtual const log4cplus::tstring & getMessage () const
virtual unsigned int getType () const
virtual std::unique_ptr
*
< InternalLoggingEvent > clone () const
const log4cplus::tstring & getLoggerName () const
LogLevel getLogLevel () const
const log4cplus::tstring & getNDC () const
MappedDiagnosticContextMap const & getMDCCopy () const
tstring const & getMDC (tstring const &key) const
const log4cplus::tstring & getThread () const
const log4cplus::tstring & getThread2 () const
const log4cplus::helpers::Time & getTimestamp () const
const log4cplus::tstring & getFile () const
int getLine () const
log4cplus::tstring const & getFunction () const
void gatherThreadSpecificData () const
void swap (InternalLoggingEvent &)
log4cplus::spi::InternalLoggingEvent & operator= (const log4cplus::spi::InternalLoggingEvent &rhs)
Static Public Member Functions
static unsigned int getDefaultType ()
Protected Attributes
log4cplus::tstring message
log4cplus::tstring loggerName
LogLevel ll
log4cplus::tstring ndc
MappedDiagnosticContextMap mdc
log4cplus::tstring thread
log4cplus::tstring thread2
log4cplus::helpers::Time timestamp
log4cplus::tstring file
log4cplus::tstring function
int line
bool threadCached
bool thread2Cached
bool ndcCached
bool mdcCached
Detailed Description
The internal representation of logging events. When an affirmative decision is made to log then a InternalLoggingEvent instance is created. This instance is passed around to the different log4cplus components.
This class is of concern to those wishing to extend log4cplus.
Constructor & Destructor Documentation
log4cplus::spi::InternalLoggingEvent::InternalLoggingEvent (const log4cplus::tstring & logger, LogLevel loglevel, const log4cplus::tstring & message, const char * filename, int line, const char * function = nullptr)
Instantiate a LoggingEvent from the supplied parameters.
Parameters
logger The logger of this event.
loglevel The LogLevel of this event.
message The message of this event.
filename Name of file where this event has occurred, can be NULL.
line Line number in file specified by the filename parameter.
function Name of function that is logging this event.
log4cplus::spi::InternalLoggingEvent::InternalLoggingEvent (const log4cplus::tstring & logger, LogLevel loglevel, const log4cplus::tstring & ndc, MappedDiagnosticContextMap const & mdc, const log4cplus::tstring & message, const log4cplus::tstring & thread, log4cplus::helpers::Time time, const log4cplus::tstring & file, int line, const log4cplus::tstring & function = log4cplus::tstring())
log4cplus::spi::InternalLoggingEvent::InternalLoggingEvent ()
log4cplus::spi::InternalLoggingEvent::InternalLoggingEvent (const log4cplus::spi::InternalLoggingEvent & rhs)
virtual log4cplus::spi::InternalLoggingEvent::~InternalLoggingEvent () [virtual]
Member Function Documentation
virtual std::unique_ptr<InternalLoggingEvent> log4cplus::spi::InternalLoggingEvent::clone () const [virtual]
Returns a copy of this object. Derived classes should override this method.
void log4cplus::spi::InternalLoggingEvent::gatherThreadSpecificData () const
static unsigned int log4cplus::spi::InternalLoggingEvent::getDefaultType () [static]
const log4cplus::tstring& log4cplus::spi::InternalLoggingEvent::getFile () const [inline]
The is the file where this log statement was written
log4cplus::tstring const& log4cplus::spi::InternalLoggingEvent::getFunction () const [inline]
int log4cplus::spi::InternalLoggingEvent::getLine () const [inline]
The is the line where this log statement was written
const log4cplus::tstring& log4cplus::spi::InternalLoggingEvent::getLoggerName () const [inline]
The logger of the logging event. It is set by the LoggingEvent constructor.
LogLevel log4cplus::spi::InternalLoggingEvent::getLogLevel () const [inline]
LogLevel of logging event.
tstring const& log4cplus::spi::InternalLoggingEvent::getMDC (tstring const & key) const
MappedDiagnosticContextMap const& log4cplus::spi::InternalLoggingEvent::getMDCCopy () const [inline]
References log4cplus::MDC::getContext(), and log4cplus::getMDC().
virtual const log4cplus::tstring& log4cplus::spi::InternalLoggingEvent::getMessage () const [virtual]
The application supplied message of logging event.
const log4cplus::tstring& log4cplus::spi::InternalLoggingEvent::getNDC () const [inline]
The nested diagnostic context (NDC) of logging event.
References log4cplus::NDC::get(), and log4cplus::getNDC().
const log4cplus::tstring& log4cplus::spi::InternalLoggingEvent::getThread () const [inline]
The name of thread in which this logging event was generated.
References log4cplus::thread::getCurrentThreadName().
const log4cplus::tstring& log4cplus::spi::InternalLoggingEvent::getThread2 () const [inline]
The alternative name of thread in which this logging event was generated.
References log4cplus::thread::getCurrentThreadName2().
const log4cplus::helpers::Time& log4cplus::spi::InternalLoggingEvent::getTimestamp () const [inline]
Time stamp when the event was created.
virtual unsigned int log4cplus::spi::InternalLoggingEvent::getType () const [virtual]
Returns the 'type' of InternalLoggingEvent. Derived classes should override this method. (NOTE: Values <= 1000 are reserved for log4cplus and should not be used.)
log4cplus::spi::InternalLoggingEvent& log4cplus::spi::InternalLoggingEvent::operator= (const log4cplus::spi::InternalLoggingEvent & rhs)
void log4cplus::spi::InternalLoggingEvent::setFunction (char const * func)
void log4cplus::spi::InternalLoggingEvent::setFunction (log4cplus::tstring const &)
void log4cplus::spi::InternalLoggingEvent::setLoggingEvent (const log4cplus::tstring & logger, LogLevel ll, const log4cplus::tstring & message, const char * filename, int line, const char * function = nullptr)
void log4cplus::spi::InternalLoggingEvent::swap (InternalLoggingEvent &)
Member Data Documentation
log4cplus::tstring log4cplus::spi::InternalLoggingEvent::file [protected]
log4cplus::tstring log4cplus::spi::InternalLoggingEvent::function [protected]
int log4cplus::spi::InternalLoggingEvent::line [protected]
LogLevel log4cplus::spi::InternalLoggingEvent::ll [protected]
log4cplus::tstring log4cplus::spi::InternalLoggingEvent::loggerName [protected]
MappedDiagnosticContextMap log4cplus::spi::InternalLoggingEvent::mdc [mutable], [protected]
bool log4cplus::spi::InternalLoggingEvent::mdcCached [mutable], [protected]
Indicates whether or not the MDC has been retrieved.
log4cplus::tstring log4cplus::spi::InternalLoggingEvent::message [protected]
log4cplus::tstring log4cplus::spi::InternalLoggingEvent::ndc [mutable], [protected]
bool log4cplus::spi::InternalLoggingEvent::ndcCached [mutable], [protected]
Indicates whether or not the NDC has been retrieved.
log4cplus::tstring log4cplus::spi::InternalLoggingEvent::thread [mutable], [protected]
log4cplus::tstring log4cplus::spi::InternalLoggingEvent::thread2 [mutable], [protected]
bool log4cplus::spi::InternalLoggingEvent::thread2Cached [mutable], [protected]
bool log4cplus::spi::InternalLoggingEvent::threadCached [mutable], [protected]
Indicates whether or not the Threadname has been retrieved.
log4cplus::helpers::Time log4cplus::spi::InternalLoggingEvent::timestamp [protected]
The documentation for this class was generated from the following file:
/home/roger/NetBeansProjects/log4cplus/include/log4cplus/spi/loggingevent.h