pion::plugin_ptr< InterfaceClassType > Class Template Reference
#include <plugin.hpp>
Public Member Functions
plugin_ptr (void)
default constructor & destructor
virtual ~plugin_ptr ()
plugin_ptr (const plugin_ptr &p)
copy constructor
plugin_ptr & operator= (const plugin_ptr &p)
assignment operator
InterfaceClassType * create (void)
creates a new instance of the plug-in object
void destroy (InterfaceClassType *object_ptr)
destroys an instance of the plug-in object
Protected Types
typedef InterfaceClassType * CreateObjectFunction (void)
data type for a function that is used to create object instances
typedef void DestroyObjectFunction (InterfaceClassType *)
data type for a function that is used to destroy object instances
Additional Inherited Members
Detailed Description
template<typename InterfaceClassType>class pion::plugin_ptr< InterfaceClassType >
plugin_ptr: smart pointer that manages plug-in code loaded from shared object libraries
Member Typedef Documentation
template<typename InterfaceClassType> typedef InterfaceClassType* pion::plugin_ptr< InterfaceClassType >::CreateObjectFunction(void) [protected]
data type for a function that is used to create object instances
template<typename InterfaceClassType> typedef void pion::plugin_ptr< InterfaceClassType >::DestroyObjectFunction(InterfaceClassType *) [protected]
data type for a function that is used to destroy object instances
Constructor & Destructor Documentation
template<typename InterfaceClassType> pion::plugin_ptr< InterfaceClassType >::plugin_ptr (void) [inline]
default constructor & destructor
template<typename InterfaceClassType> virtual pion::plugin_ptr< InterfaceClassType >::~plugin_ptr () [inline], [virtual]
template<typename InterfaceClassType> pion::plugin_ptr< InterfaceClassType >::plugin_ptr (const plugin_ptr< InterfaceClassType > & p) [inline]
copy constructor
Member Function Documentation
template<typename InterfaceClassType> InterfaceClassType* pion::plugin_ptr< InterfaceClassType >::create (void) [inline]
creates a new instance of the plug-in object
References pion::plugin::get_create_function().
Referenced by pion::plugin_manager< PluginType >::load().
template<typename InterfaceClassType> void pion::plugin_ptr< InterfaceClassType >::destroy (InterfaceClassType * object_ptr) [inline]
destroys an instance of the plug-in object
References pion::plugin::get_destroy_function().
template<typename InterfaceClassType> plugin_ptr& pion::plugin_ptr< InterfaceClassType >::operator= (const plugin_ptr< InterfaceClassType > & p) [inline]
assignment operator
References pion::plugin::grab_data().
The documentation for this class was generated from the following file:
include/pion/plugin.hpp