pion::test Namespace Reference
Classes
class safe_xml_log_formatter
thread-safe version of Boost.Test's xml_log_formatter class
struct config
Functions
static char * trim (char *str)
static bool read_lines_from_file (const std::string &filename, std::list< std::string > &lines)
static bool check_files_match (const std::string &fileA, const std::string &fileB)
static bool check_files_exact_match (const std::string &fileA, const std::string &fileB, bool ignore_line_endings=false)
Function Documentation
static bool pion::test::check_files_exact_match (const std::string & fileA, const std::string & fileB, bool ignore_line_endings = false) [inline], [static]
References trim().
static bool pion::test::check_files_match (const std::string & fileA, const std::string & fileB) [inline], [static]
References read_lines_from_file().
static bool pion::test::read_lines_from_file (const std::string & filename, std::list< std::string > & lines) [inline], [static]
References trim().
Referenced by check_files_match().
static char* pion::test::trim (char * str) [inline], [static]
Referenced by check_files_exact_match(), read_lines_from_file(), and pion::http::message::update_content_length_using_header().