pion Namespace Reference
Namespaces
error
http
spdy
tcp
test
Classes
class admin_rights
struct algorithm
class exception
struct iequal_to
struct ihash
struct logger
class plugin
class plugin_ptr
class plugin_instance_ptr
class plugin_manager
class process
class scheduler
class multi_thread_scheduler
class single_service_scheduler
class one_to_one_scheduler
class user
class user_manager
Typedefs
typedef PION_HASH_MULTIMAP
*
< std::string, std::string,
*
ihash, iequal_to > ihash_multimap
data type for case-insensitive dictionary of strings
typedef int log_appender
typedef log_appender * log_appender_ptr
typedef boost::shared_ptr< user > user_ptr
data type for a user pointer
typedef boost::shared_ptr
*
< user_manager > user_manager_ptr
data type for a user_manager pointer
Functions
template<class T >
static std::string diagnostic_information (T const &e)
void handle_signal (int)
Typedef Documentation
typedef PION_HASH_MULTIMAP<std::string, std::string, ihash, iequal_to > pion::ihash_multimap
data type for case-insensitive dictionary of strings
typedef int pion::log_appender
typedef log_appender* pion::log_appender_ptr
typedef boost::shared_ptr<user_manager> pion::user_manager_ptr
data type for a user_manager pointer
typedef boost::shared_ptr<user> pion::user_ptr
data type for a user pointer
Function Documentation
template<class T > static std::string pion::diagnostic_information (T const & e) [inline], [static]
static method that generates a meaningful diagnostic message from exceptions
Parameters
e reference to an exception object
Returns
std::string descriptive error message
Referenced by pion::http::server::handle_request(), pion::http::plugin_server::load_service_config(), and pion::scheduler::process_service_work().
void pion::handle_signal (int)
References pion::process::shutdown().
Referenced by pion::process::initialize().